import { prisma } from "@/lib/prisma"
import type { PlannedExpenseUpdateInput } from "@/lib/validations/finance-planner"
import { ExpenseBucket, PlanEntrySource, Prisma, type Subscription } from "@prisma/client"
import { revalidatePath } from "next/cache"

type SubscriptionExpenseSyncInput = Pick<
  Subscription,
  | "id"
  | "userId"
  | "name"
  | "planLabel"
  | "price"
  | "currency"
  | "nextBillingDate"
  | "active"
  | "paymentMethodId"
>

type PrismaClientLike = typeof prisma | Prisma.TransactionClient

function monthFromDate(date: Date) {
  return {
    year: date.getFullYear(),
    month: date.getMonth() + 1,
  }
}

async function getOrCreatePlan(
  client: PrismaClientLike,
  userId: string,
  date: Date
) {
  const { year, month } = monthFromDate(date)

  return client.monthlyPlan.upsert({
    where: { userId_year_month: { userId, year, month } },
    create: { userId, year, month },
    update: {},
    select: { id: true },
  })
}

function buildExpenseDescription(subscription: SubscriptionExpenseSyncInput) {
  return subscription.planLabel?.trim() || null
}

export async function upsertSubscriptionExpense(
  userId: string,
  subscription: SubscriptionExpenseSyncInput,
  client: PrismaClientLike = prisma
) {
  if (!subscription.active) {
    await deleteSubscriptionExpense(userId, subscription.id, client)
    return null
  }

  const plan = await getOrCreatePlan(client, userId, subscription.nextBillingDate)
  const existing = await client.plannedExpense.findFirst({
    where: {
      subscriptionId: subscription.id,
      monthlyPlan: { userId },
    },
    select: { id: true },
  })

  const data = {
    monthlyPlanId: plan.id,
    name: subscription.name,
    description: buildExpenseDescription(subscription),
    amount: subscription.price,
    currency: subscription.currency,
    expenseBucket: ExpenseBucket.MONTHLY_BILLS,
    dueDate: subscription.nextBillingDate,
    source: PlanEntrySource.SUBSCRIPTION,
    isAutoGenerated: true,
    isLocked: true,
    paymentMethodId: subscription.paymentMethodId,
    paymentCardId: null,
    creditCardInvoiceId: null,
    installmentPurchaseId: null,
    installmentNumber: null,
    installmentTotal: null,
    recurrenceKind: null,
    recurrenceGroupId: null,
  } satisfies Prisma.PlannedExpenseUncheckedUpdateInput

  if (existing) {
    return client.plannedExpense.update({
      where: { id: existing.id },
      data,
      select: { id: true },
    })
  }

  return client.plannedExpense.create({
    data: {
      ...data,
      subscriptionId: subscription.id,
    },
    select: { id: true },
  })
}

export async function deleteSubscriptionExpense(
  userId: string,
  subscriptionId: string,
  client: PrismaClientLike = prisma
) {
  return client.plannedExpense.deleteMany({
    where: {
      subscriptionId,
      monthlyPlan: { userId },
    },
  })
}

export async function syncSubscriptionFromExpense(
  userId: string,
  expenseId: string,
  data: PlannedExpenseUpdateInput,
  client: PrismaClientLike = prisma
) {
  const expense = await client.plannedExpense.findFirst({
    where: {
      id: expenseId,
      monthlyPlan: { userId },
      subscriptionId: { not: null },
    },
    include: {
      subscription: true,
    },
  })

  if (!expense?.subscription) return null

  const updateData: Prisma.SubscriptionUpdateInput = {}
  const nextBillingDate =
    data.dueDate !== undefined && data.dueDate !== null ? data.dueDate : undefined

  if (data.name !== undefined) updateData.name = data.name
  if (data.description !== undefined) {
    updateData.planLabel = data.description?.trim() || null
  }
  if (data.amount !== undefined) updateData.price = new Prisma.Decimal(data.amount)
  if (data.currency !== undefined) updateData.currency = data.currency
  if (nextBillingDate) updateData.nextBillingDate = nextBillingDate
  if (data.paymentMethodId !== undefined) {
    updateData.paymentMethod = data.paymentMethodId
      ? { connect: { id: data.paymentMethodId } }
      : { disconnect: true }
  }

  if (Object.keys(updateData).length === 0) return expense.subscription

  const subscription = await client.subscription.update({
    where: { id: expense.subscription.id },
    data: updateData,
  })

  await upsertSubscriptionExpense(userId, subscription, client)

  return subscription
}

export async function deleteSubscriptionFromExpense(
  userId: string,
  expenseId: string,
  client: PrismaClientLike = prisma
) {
  const expense = await client.plannedExpense.findFirst({
    where: {
      id: expenseId,
      monthlyPlan: { userId },
      subscriptionId: { not: null },
    },
    select: { subscriptionId: true },
  })

  if (!expense?.subscriptionId) return null

  await client.plannedExpense.deleteMany({
    where: {
      subscriptionId: expense.subscriptionId,
      monthlyPlan: { userId },
    },
  })
  await client.subscription.delete({
    where: { id: expense.subscriptionId },
  })

  return { subscriptionId: expense.subscriptionId }
}

export function revalidateSubscriptionExpenseSyncPaths() {
  revalidatePath("/dashboard")
  revalidatePath("/subscriptions")
  revalidatePath("/finance-planner")
}
