import { describe, it, expect } from "vitest"
import type { RootState } from "@/store"
import {
  selectFinanceState,
  selectFinanceLoading,
  selectFinanceError,
  selectSelectedYear,
  selectSelectedMonth,
  selectSelectedMonthRef,
  selectMonthlyPlan,
  selectMonthSummary,
  selectFinanceFormOptions,
  selectPlannedIncomes,
  selectPlannedExpenses,
  selectPlannedIncomeById,
  selectPlannedExpenseById,
  selectReceivedIncomes,
  selectPendingIncomes,
  selectPaidExpenses,
  selectPendingExpenses,
  selectMonthlyBillsExpenses,
  selectCreditCardExpenses,
  selectFixedCardExpenses,
  selectOtherExpenses,
  selectPaymentMethodsOptions,
  selectSubscriptionsOptions,
  selectSummaryIncomeTotal,
  selectSummaryReceivedTotal,
  selectSummaryExpenseTotal,
  selectSummaryPaidTotal,
  selectSummarySubscriptionTotal,
  selectSummaryCreditCardTotal,
  selectSummaryBalance,
  selectSummaryPendingIncomeTotal,
  selectSummaryPendingExpenseTotal,
  selectIsFinancePlanReady,
  selectIsFinanceSummaryReady,
  selectIsFinanceFormOptionsReady,
} from "@/store/selectors/finance"

// ---------------------------------------------------------------------------
// Factories
// ---------------------------------------------------------------------------

type Override<T> = { [K in keyof T]?: T[K] }

const makeIncome = (overrides: Override<SerializedIncome> = {}): SerializedIncome => ({
  id: "income-1",
  monthlyPlanId: "plan-1",
  name: "Salary",
  amount: "5000",
  currency: "BRL",
  sortOrder: 0,
  description: null,
  expectedDate: null,
  receivedAt: null,
  isReceived: false,
  recurrenceKind: null,
  recurrenceGroupId: null,
  recurrenceNumber: null,
  recurrenceTotal: null,
  createdAt: "2026-07-01T00:00:00.000Z",
  updatedAt: "2026-07-01T00:00:00.000Z",
  ...overrides,
} as SerializedIncome)

const makeExpense = (
  overrides: Override<SerializedExpense> = {},
): SerializedExpense => ({
  id: "expense-1",
  monthlyPlanId: "plan-1",
  name: "Rent",
  merchantName: null,
  description: null,
  amount: "1500",
  currency: "BRL",
  expenseBucket: "MONTHLY_BILLS",
  sortOrder: 0,
  purchaseDate: null,
  dueDate: null,
  paidAt: null,
  isPaid: false,
  source: "MANUAL",
  isAutoGenerated: false,
  isLocked: false,
  paymentMethodId: null,
  paymentCardId: null,
  creditCardInvoiceId: null,
  subscriptionId: null,
  installmentPurchaseId: null,
  paymentMethod: null,
  paymentCard: null,
  creditCardInvoice: null,
  subscription: null,
  installmentPurchase: null,
  createdAt: "2026-07-01T00:00:00.000Z",
  updatedAt: "2026-07-01T00:00:00.000Z",
  ...overrides,
} as SerializedExpense)

type SerializedIncome = NonNullable<
  RootState["finance"]["plan"]
>["incomes"][number]

type SerializedExpense = NonNullable<
  RootState["finance"]["plan"]
>["expenses"][number]

type Summary = NonNullable<RootState["finance"]["summary"]>

type FormOptions = NonNullable<RootState["finance"]["formOptions"]>

const makeSummary = (overrides: Override<Summary> = {}): Summary => ({
  incomeTotal: "5000",
  receivedTotal: "3000",
  expenseTotal: "2000",
  paidTotal: "1500",
  subscriptionTotal: "500",
  creditCardTotal: "800",
  balance: "3000",
  pendingIncomeTotal: "2000",
  pendingExpenseTotal: "500",
  ...overrides,
} as Summary)

const makeFormOptions = (
  overrides: Override<FormOptions> = {},
): FormOptions => ({
  paymentMethods: [
    {
      id: "pm-1",
      name: "Nubank",
      type: "CREDIT_CARD",
      paymentCard: {
        id: "card-1",
        nickname: "Nubank Visa",
        brand: "Visa",
        last4: "1234",
        dueDay: 15,
      },
    },
  ],
  subscriptions: [
    {
      id: "sub-1",
      name: "Netflix",
      price: "39.90",
      currency: "BRL",
      paymentMethodId: "pm-1",
    },
  ],
  creditCardInvoices: [
    {
      id: "inv-1",
      year: 2026,
      month: 7,
      status: "OPEN",
      total: "1200",
      currency: "BRL",
      paymentCardId: "card-1",
    },
  ],
  installmentPurchases: [
    {
      id: "inst-1",
      name: "MacBook",
      totalAmount: "12000",
      currency: "BRL",
      installmentCount: 12,
      paymentCardId: "card-1",
    },
  ],
  ...overrides,
} as FormOptions)

/**
 * Build a partial RootState with sensible defaults for the auth and
 * subscriptions slices, allowing override of the finance slice fields.
 */
function makeRootState(
  overrides: Partial<RootState["finance"]> = {},
): RootState {
  return {
    auth: {
      session: null,
      profile: null,
      isLoading: false,
      error: null,
    },
    subscriptions: {
      items: [],
      formOptions: null,
      isLoading: false,
      error: null,
    },
    finance: {
      selectedYear: 2026,
      selectedMonth: 7,
      plan: null,
      summary: null,
      formOptions: null,
      isLoading: false,
      error: null,
      ...overrides,
    },
  } as RootState
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("selectFinanceState", () => {
  it("returns the entire finance slice", () => {
    const state = makeRootState({ isLoading: true })
    expect(selectFinanceState(state)).toBe(state.finance)
  })
})

describe("selectFinanceLoading", () => {
  it("returns isLoading when true", () => {
    const state = makeRootState({ isLoading: true })
    expect(selectFinanceLoading(state)).toBe(true)
  })

  it("returns isLoading when false", () => {
    const state = makeRootState({ isLoading: false })
    expect(selectFinanceLoading(state)).toBe(false)
  })
})

describe("selectFinanceError", () => {
  it("returns the error message", () => {
    const state = makeRootState({ error: "Something went wrong" })
    expect(selectFinanceError(state)).toBe("Something went wrong")
  })

  it("returns null when there is no error", () => {
    const state = makeRootState({ error: null })
    expect(selectFinanceError(state)).toBeNull()
  })
})

describe("selectSelectedYear", () => {
  it("returns the selected year", () => {
    const state = makeRootState({ selectedYear: 2026 })
    expect(selectSelectedYear(state)).toBe(2026)
  })
})

describe("selectSelectedMonth", () => {
  it("returns the selected month", () => {
    const state = makeRootState({ selectedMonth: 7 })
    expect(selectSelectedMonth(state)).toBe(7)
  })
})

describe("selectSelectedMonthRef", () => {
  it("returns { year, month } object", () => {
    const state = makeRootState({ selectedYear: 2026, selectedMonth: 7 })
    expect(selectSelectedMonthRef(state)).toEqual({ year: 2026, month: 7 })
  })
})

describe("selectMonthlyPlan", () => {
  it("returns the plan object when present", () => {
    const plan = { id: "plan-1" } as RootState["finance"]["plan"]
    const state = makeRootState({ plan })
    expect(selectMonthlyPlan(state)).toBe(plan)
  })

  it("returns null when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectMonthlyPlan(state)).toBeNull()
  })
})

describe("selectMonthSummary", () => {
  it("returns the summary object when present", () => {
    const summary = makeSummary()
    const state = makeRootState({ summary })
    expect(selectMonthSummary(state)).toBe(summary)
  })

  it("returns null when summary is null", () => {
    const state = makeRootState({ summary: null })
    expect(selectMonthSummary(state)).toBeNull()
  })
})

describe("selectFinanceFormOptions", () => {
  it("returns the formOptions object when present", () => {
    const formOptions = makeFormOptions()
    const state = makeRootState({ formOptions })
    expect(selectFinanceFormOptions(state)).toBe(formOptions)
  })

  it("returns null when formOptions is null", () => {
    const state = makeRootState({ formOptions: null })
    expect(selectFinanceFormOptions(state)).toBeNull()
  })
})

// ---------------------------------------------------------------------------
// selectPlannedIncomes / selectPlannedExpenses
// ---------------------------------------------------------------------------

describe("selectPlannedIncomes", () => {
  it("returns incomes array when plan exists", () => {
    const incomes = [makeIncome({ id: "i-1" }), makeIncome({ id: "i-2" })]
    const state = makeRootState({
      plan: { incomes, expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPlannedIncomes(state)).toEqual(incomes)
  })

  it("returns empty array when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectPlannedIncomes(state)).toEqual([])
  })

  it("returns empty array when plan has no incomes", () => {
    const state = makeRootState({
      plan: { incomes: [], expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPlannedIncomes(state)).toEqual([])
  })
})

describe("selectPlannedExpenses", () => {
  it("returns expenses array when plan exists", () => {
    const expenses = [makeExpense({ id: "e-1" }), makeExpense({ id: "e-2" })]
    const state = makeRootState({
      plan: { incomes: [], expenses } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPlannedExpenses(state)).toEqual(expenses)
  })

  it("returns empty array when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectPlannedExpenses(state)).toEqual([])
  })

  it("returns empty array when plan has no expenses", () => {
    const state = makeRootState({
      plan: { incomes: [], expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPlannedExpenses(state)).toEqual([])
  })
})

// ---------------------------------------------------------------------------
// selectPlannedIncomeById / selectPlannedExpenseById (factory selectors)
// ---------------------------------------------------------------------------

describe("selectPlannedIncomeById", () => {
  it("returns the matching income when found", () => {
    const incomes = [
      makeIncome({ id: "i-1", name: "Salary" }),
      makeIncome({ id: "i-2", name: "Freelance" }),
    ]
    const state = makeRootState({
      plan: { incomes, expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPlannedIncomeById("i-2")(state)?.name).toBe("Freelance")
  })

  it("returns null when id does not match", () => {
    const incomes = [makeIncome({ id: "i-1" })]
    const state = makeRootState({
      plan: { incomes, expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPlannedIncomeById("nonexistent")(state)).toBeNull()
  })

  it("returns null when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectPlannedIncomeById("i-1")(state)).toBeNull()
  })

  it("returns null when incomes array is empty", () => {
    const state = makeRootState({
      plan: { incomes: [], expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPlannedIncomeById("i-1")(state)).toBeNull()
  })
})

describe("selectPlannedExpenseById", () => {
  it("returns the matching expense when found", () => {
    const expenses = [
      makeExpense({ id: "e-1", name: "Rent" }),
      makeExpense({ id: "e-2", name: "Internet" }),
    ]
    const state = makeRootState({
      plan: { incomes: [], expenses } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPlannedExpenseById("e-1")(state)?.name).toBe("Rent")
  })

  it("returns null when id does not match", () => {
    const expenses = [makeExpense({ id: "e-1" })]
    const state = makeRootState({
      plan: { incomes: [], expenses } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPlannedExpenseById("nonexistent")(state)).toBeNull()
  })

  it("returns null when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectPlannedExpenseById("e-1")(state)).toBeNull()
  })

  it("returns null when expenses array is empty", () => {
    const state = makeRootState({
      plan: { incomes: [], expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPlannedExpenseById("e-1")(state)).toBeNull()
  })
})

// ---------------------------------------------------------------------------
// Filter selectors (boolean flags)
// ---------------------------------------------------------------------------

describe("selectReceivedIncomes", () => {
  it("returns only received incomes", () => {
    const incomes = [
      makeIncome({ id: "i-1", isReceived: true }),
      makeIncome({ id: "i-2", isReceived: false }),
      makeIncome({ id: "i-3", isReceived: true }),
    ]
    const state = makeRootState({
      plan: { incomes, expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    const result = selectReceivedIncomes(state)
    expect(result).toHaveLength(2)
    expect(result.every((i) => i.isReceived)).toBe(true)
    expect(result.map((i) => i.id)).toEqual(["i-1", "i-3"])
  })

  it("returns empty array when no incomes are received", () => {
    const incomes = [
      makeIncome({ id: "i-1", isReceived: false }),
      makeIncome({ id: "i-2", isReceived: false }),
    ]
    const state = makeRootState({
      plan: { incomes, expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    expect(selectReceivedIncomes(state)).toEqual([])
  })

  it("returns empty array when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectReceivedIncomes(state)).toEqual([])
  })
})

describe("selectPendingIncomes", () => {
  it("returns only non-received incomes", () => {
    const incomes = [
      makeIncome({ id: "i-1", isReceived: true }),
      makeIncome({ id: "i-2", isReceived: false }),
      makeIncome({ id: "i-3", isReceived: false }),
    ]
    const state = makeRootState({
      plan: { incomes, expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    const result = selectPendingIncomes(state)
    expect(result).toHaveLength(2)
    expect(result.every((i) => !i.isReceived)).toBe(true)
    expect(result.map((i) => i.id)).toEqual(["i-2", "i-3"])
  })

  it("returns empty array when all incomes are received", () => {
    const incomes = [
      makeIncome({ id: "i-1", isReceived: true }),
      makeIncome({ id: "i-2", isReceived: true }),
    ]
    const state = makeRootState({
      plan: { incomes, expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPendingIncomes(state)).toEqual([])
  })

  it("returns empty array when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectPendingIncomes(state)).toEqual([])
  })
})

describe("selectPaidExpenses", () => {
  it("returns only paid expenses", () => {
    const expenses = [
      makeExpense({ id: "e-1", isPaid: true }),
      makeExpense({ id: "e-2", isPaid: false }),
      makeExpense({ id: "e-3", isPaid: true }),
    ]
    const state = makeRootState({
      plan: { incomes: [], expenses } as unknown as RootState["finance"]["plan"],
    })
    const result = selectPaidExpenses(state)
    expect(result).toHaveLength(2)
    expect(result.every((e) => e.isPaid)).toBe(true)
    expect(result.map((e) => e.id)).toEqual(["e-1", "e-3"])
  })

  it("returns empty array when no expenses are paid", () => {
    const expenses = [
      makeExpense({ id: "e-1", isPaid: false }),
      makeExpense({ id: "e-2", isPaid: false }),
    ]
    const state = makeRootState({
      plan: { incomes: [], expenses } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPaidExpenses(state)).toEqual([])
  })

  it("returns empty array when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectPaidExpenses(state)).toEqual([])
  })
})

describe("selectPendingExpenses", () => {
  it("returns only unpaid expenses", () => {
    const expenses = [
      makeExpense({ id: "e-1", isPaid: true }),
      makeExpense({ id: "e-2", isPaid: false }),
      makeExpense({ id: "e-3", isPaid: false }),
    ]
    const state = makeRootState({
      plan: { incomes: [], expenses } as unknown as RootState["finance"]["plan"],
    })
    const result = selectPendingExpenses(state)
    expect(result).toHaveLength(2)
    expect(result.every((e) => !e.isPaid)).toBe(true)
    expect(result.map((e) => e.id)).toEqual(["e-2", "e-3"])
  })

  it("returns empty array when all expenses are paid", () => {
    const expenses = [
      makeExpense({ id: "e-1", isPaid: true }),
      makeExpense({ id: "e-2", isPaid: true }),
    ]
    const state = makeRootState({
      plan: { incomes: [], expenses } as unknown as RootState["finance"]["plan"],
    })
    expect(selectPendingExpenses(state)).toEqual([])
  })

  it("returns empty array when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectPendingExpenses(state)).toEqual([])
  })
})

// ---------------------------------------------------------------------------
// Bucket selectors (expenseBucket enum)
// ---------------------------------------------------------------------------

function makeBucketState(_bucket: string) {
  const expenses = [
    makeExpense({ id: "e-mb", expenseBucket: "MONTHLY_BILLS" as const }),
    makeExpense({ id: "e-cc", expenseBucket: "CREDIT_CARD" as const }),
    makeExpense({ id: "e-fc", expenseBucket: "FIXED_CARD" as const }),
    makeExpense({ id: "e-ot", expenseBucket: "OTHER" as const }),
  ]
  return makeRootState({
    plan: { incomes: [], expenses } as unknown as RootState["finance"]["plan"],
  })
}

describe("selectMonthlyBillsExpenses", () => {
  it("filters expenses by MONTHLY_BILLS bucket", () => {
    const state = makeBucketState("MONTHLY_BILLS")
    const result = selectMonthlyBillsExpenses(state)
    expect(result).toHaveLength(1)
    expect(result[0]?.expenseBucket).toBe("MONTHLY_BILLS")
  })

  it("returns empty array when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectMonthlyBillsExpenses(state)).toEqual([])
  })
})

describe("selectCreditCardExpenses", () => {
  it("filters expenses by CREDIT_CARD bucket", () => {
    const state = makeBucketState("CREDIT_CARD")
    const result = selectCreditCardExpenses(state)
    expect(result).toHaveLength(1)
    expect(result[0]?.expenseBucket).toBe("CREDIT_CARD")
  })

  it("returns empty array when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectCreditCardExpenses(state)).toEqual([])
  })
})

describe("selectFixedCardExpenses", () => {
  it("filters expenses by FIXED_CARD bucket", () => {
    const state = makeBucketState("FIXED_CARD")
    const result = selectFixedCardExpenses(state)
    expect(result).toHaveLength(1)
    expect(result[0]?.expenseBucket).toBe("FIXED_CARD")
  })

  it("returns empty array when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectFixedCardExpenses(state)).toEqual([])
  })
})

describe("selectOtherExpenses", () => {
  it("filters expenses by OTHER bucket", () => {
    const state = makeBucketState("OTHER")
    const result = selectOtherExpenses(state)
    expect(result).toHaveLength(1)
    expect(result[0]?.expenseBucket).toBe("OTHER")
  })

  it("returns empty array when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectOtherExpenses(state)).toEqual([])
  })
})

describe("bucket selectors integration", () => {
  it("each bucket selector returns only its own expenses", () => {
    const expenses = [
      makeExpense({ id: "e-1", expenseBucket: "MONTHLY_BILLS" as const }),
      makeExpense({ id: "e-2", expenseBucket: "CREDIT_CARD" as const }),
      makeExpense({ id: "e-3", expenseBucket: "FIXED_CARD" as const }),
      makeExpense({ id: "e-4", expenseBucket: "OTHER" as const }),
      makeExpense({ id: "e-5", expenseBucket: "MONTHLY_BILLS" as const }),
    ]
    const state = makeRootState({
      plan: { incomes: [], expenses } as unknown as RootState["finance"]["plan"],
    })

    expect(selectMonthlyBillsExpenses(state)).toHaveLength(2)
    expect(selectCreditCardExpenses(state)).toHaveLength(1)
    expect(selectFixedCardExpenses(state)).toHaveLength(1)
    expect(selectOtherExpenses(state)).toHaveLength(1)

    expect(
      selectMonthlyBillsExpenses(state).every((e) => e.expenseBucket === "MONTHLY_BILLS"),
    ).toBe(true)
    expect(
      selectCreditCardExpenses(state).every((e) => e.expenseBucket === "CREDIT_CARD"),
    ).toBe(true)
    expect(
      selectFixedCardExpenses(state).every((e) => e.expenseBucket === "FIXED_CARD"),
    ).toBe(true)
    expect(
      selectOtherExpenses(state).every((e) => e.expenseBucket === "OTHER"),
    ).toBe(true)
  })
})

// ---------------------------------------------------------------------------
// Form option selectors
// ---------------------------------------------------------------------------

describe("selectPaymentMethodsOptions", () => {
  it("returns payment methods when formOptions is present", () => {
    const formOptions = makeFormOptions({
      paymentMethods: [
        {
          id: "pm-1",
          name: "Nubank",
          type: "CREDIT_CARD",
          paymentCard: null,
        },
      ],
    })
    const state = makeRootState({ formOptions })
    expect(selectPaymentMethodsOptions(state)).toEqual([
      { id: "pm-1", name: "Nubank", type: "CREDIT_CARD", paymentCard: null },
    ])
  })

  it("returns empty array when formOptions is null", () => {
    const state = makeRootState({ formOptions: null })
    expect(selectPaymentMethodsOptions(state)).toEqual([])
  })

  it("returns empty array when paymentMethods is empty", () => {
    const formOptions = makeFormOptions({ paymentMethods: [] })
    const state = makeRootState({ formOptions })
    expect(selectPaymentMethodsOptions(state)).toEqual([])
  })
})

describe("selectSubscriptionsOptions", () => {
  it("returns subscriptions when formOptions is present", () => {
    const formOptions = makeFormOptions({
      subscriptions: [
        { id: "sub-1", name: "Netflix", price: "39.90", currency: "BRL", paymentMethodId: null },
      ],
    })
    const state = makeRootState({ formOptions })
    expect(selectSubscriptionsOptions(state)).toEqual([
      { id: "sub-1", name: "Netflix", price: "39.90", currency: "BRL", paymentMethodId: null },
    ])
  })

  it("returns empty array when formOptions is null", () => {
    const state = makeRootState({ formOptions: null })
    expect(selectSubscriptionsOptions(state)).toEqual([])
  })

  it("returns empty array when subscriptions is empty", () => {
    const formOptions = makeFormOptions({ subscriptions: [] })
    const state = makeRootState({ formOptions })
    expect(selectSubscriptionsOptions(state)).toEqual([])
  })
})

// ---------------------------------------------------------------------------
// Summary number selectors (toNumber conversion)
// ---------------------------------------------------------------------------

describe("summary number selectors", () => {
  describe("selectSummaryIncomeTotal", () => {
    it("returns parsed number when summary has incomeTotal string", () => {
      const state = makeRootState({ summary: makeSummary({ incomeTotal: "5000" }) })
      expect(selectSummaryIncomeTotal(state)).toBe(5000)
    })

    it("returns 0 when summary is null", () => {
      const state = makeRootState({ summary: null })
      expect(selectSummaryIncomeTotal(state)).toBe(0)
    })
  })

  describe("selectSummaryReceivedTotal", () => {
    it("returns parsed number", () => {
      const state = makeRootState({ summary: makeSummary({ receivedTotal: "3200.50" }) })
      expect(selectSummaryReceivedTotal(state)).toBe(3200.5)
    })

    it("returns 0 when summary is null", () => {
      const state = makeRootState({ summary: null })
      expect(selectSummaryReceivedTotal(state)).toBe(0)
    })
  })

  describe("selectSummaryExpenseTotal", () => {
    it("returns parsed number", () => {
      const state = makeRootState({ summary: makeSummary({ expenseTotal: "2000" }) })
      expect(selectSummaryExpenseTotal(state)).toBe(2000)
    })

    it("returns 0 when summary is null", () => {
      const state = makeRootState({ summary: null })
      expect(selectSummaryExpenseTotal(state)).toBe(0)
    })
  })

  describe("selectSummaryPaidTotal", () => {
    it("returns parsed number", () => {
      const state = makeRootState({ summary: makeSummary({ paidTotal: "1500" }) })
      expect(selectSummaryPaidTotal(state)).toBe(1500)
    })

    it("returns 0 when summary is null", () => {
      const state = makeRootState({ summary: null })
      expect(selectSummaryPaidTotal(state)).toBe(0)
    })
  })

  describe("selectSummarySubscriptionTotal", () => {
    it("returns parsed number", () => {
      const state = makeRootState({ summary: makeSummary({ subscriptionTotal: "500" }) })
      expect(selectSummarySubscriptionTotal(state)).toBe(500)
    })

    it("returns 0 when summary is null", () => {
      const state = makeRootState({ summary: null })
      expect(selectSummarySubscriptionTotal(state)).toBe(0)
    })
  })

  describe("selectSummaryCreditCardTotal", () => {
    it("returns parsed number", () => {
      const state = makeRootState({ summary: makeSummary({ creditCardTotal: "800" }) })
      expect(selectSummaryCreditCardTotal(state)).toBe(800)
    })

    it("returns 0 when summary is null", () => {
      const state = makeRootState({ summary: null })
      expect(selectSummaryCreditCardTotal(state)).toBe(0)
    })
  })

  describe("selectSummaryBalance", () => {
    it("returns parsed number", () => {
      const state = makeRootState({ summary: makeSummary({ balance: "3000" }) })
      expect(selectSummaryBalance(state)).toBe(3000)
    })

    it("returns 0 when summary is null", () => {
      const state = makeRootState({ summary: null })
      expect(selectSummaryBalance(state)).toBe(0)
    })
  })

  describe("selectSummaryPendingIncomeTotal", () => {
    it("returns parsed number", () => {
      const state = makeRootState({ summary: makeSummary({ pendingIncomeTotal: "2000" }) })
      expect(selectSummaryPendingIncomeTotal(state)).toBe(2000)
    })

    it("returns 0 when summary is null", () => {
      const state = makeRootState({ summary: null })
      expect(selectSummaryPendingIncomeTotal(state)).toBe(0)
    })
  })

  describe("selectSummaryPendingExpenseTotal", () => {
    it("returns parsed number", () => {
      const state = makeRootState({ summary: makeSummary({ pendingExpenseTotal: "500" }) })
      expect(selectSummaryPendingExpenseTotal(state)).toBe(500)
    })

    it("returns 0 when summary is null", () => {
      const state = makeRootState({ summary: null })
      expect(selectSummaryPendingExpenseTotal(state)).toBe(0)
    })
  })
})

// ---------------------------------------------------------------------------
// toNumber edge cases (exercised implicitly through selectors)
// ---------------------------------------------------------------------------

describe("toNumber edge cases (via summary selectors)", () => {
  it("converts decimal string to number", () => {
    const state = makeRootState({
      summary: makeSummary({ incomeTotal: "1234.56" }),
    })
    expect(selectSummaryIncomeTotal(state)).toBe(1234.56)
  })

  it("converts '0' string to 0", () => {
    const state = makeRootState({
      summary: makeSummary({ incomeTotal: "0" }),
    })
    expect(selectSummaryIncomeTotal(state)).toBe(0)
  })

  it("returns 0 for empty string", () => {
    const state = makeRootState({
      summary: makeSummary({ incomeTotal: "" }),
    })
    expect(selectSummaryIncomeTotal(state)).toBe(0)
  })
})

// ---------------------------------------------------------------------------
// Ready-state booleans
// ---------------------------------------------------------------------------

describe("selectIsFinancePlanReady", () => {
  it("returns true when plan exists", () => {
    const state = makeRootState({
      plan: { incomes: [], expenses: [] } as unknown as RootState["finance"]["plan"],
    })
    expect(selectIsFinancePlanReady(state)).toBe(true)
  })

  it("returns false when plan is null", () => {
    const state = makeRootState({ plan: null })
    expect(selectIsFinancePlanReady(state)).toBe(false)
  })
})

describe("selectIsFinanceSummaryReady", () => {
  it("returns true when summary exists", () => {
    const state = makeRootState({ summary: makeSummary() })
    expect(selectIsFinanceSummaryReady(state)).toBe(true)
  })

  it("returns false when summary is null", () => {
    const state = makeRootState({ summary: null })
    expect(selectIsFinanceSummaryReady(state)).toBe(false)
  })
})

describe("selectIsFinanceFormOptionsReady", () => {
  it("returns true when formOptions exists", () => {
    const state = makeRootState({ formOptions: makeFormOptions() })
    expect(selectIsFinanceFormOptionsReady(state)).toBe(true)
  })

  it("returns false when formOptions is null", () => {
    const state = makeRootState({ formOptions: null })
    expect(selectIsFinanceFormOptionsReady(state)).toBe(false)
  })
})

// ---------------------------------------------------------------------------
// Full integration: combining selectors returns consistent data
// ---------------------------------------------------------------------------

describe("integration: combined selectors on populated state", () => {
  it("returns consistent derived data from a fully populated state", () => {
    const incomes = [
      makeIncome({ id: "i-1", name: "Salary", amount: "5000", isReceived: true }),
      makeIncome({ id: "i-2", name: "Freelance", amount: "1500", isReceived: false }),
    ]
    const expenses = [
      makeExpense({ id: "e-1", name: "Rent", amount: "1200", isPaid: true, expenseBucket: "MONTHLY_BILLS" as const }),
      makeExpense({ id: "e-2", name: "Netflix", amount: "39.90", isPaid: true, expenseBucket: "MONTHLY_BILLS" as const }),
      makeExpense({ id: "e-3", name: "Amazon", amount: "250", isPaid: false, expenseBucket: "OTHER" as const }),
      makeExpense({ id: "e-4", name: "Credit Card Bill", amount: "800", isPaid: false, expenseBucket: "CREDIT_CARD" as const }),
    ]
    const summary = makeSummary({
      incomeTotal: "6500",
      receivedTotal: "5000",
      expenseTotal: "1489.90",
      paidTotal: "1239.90",
    })
    const formOptions = makeFormOptions()

    const state = makeRootState({
      selectedYear: 2026,
      selectedMonth: 7,
      plan: { incomes, expenses } as unknown as RootState["finance"]["plan"],
      summary,
      formOptions,
    })

    // -- Raw state accessors --
    expect(selectFinanceState(state)).toBe(state.finance)
    expect(selectFinanceLoading(state)).toBe(false)
    expect(selectFinanceError(state)).toBeNull()
    expect(selectSelectedYear(state)).toBe(2026)
    expect(selectSelectedMonth(state)).toBe(7)
    expect(selectSelectedMonthRef(state)).toEqual({ year: 2026, month: 7 })

    // -- Plan / summary / formOptions --
    expect(selectMonthlyPlan(state)).toBeDefined()
    expect(selectMonthSummary(state)).toBe(summary)
    expect(selectFinanceFormOptions(state)).toBe(formOptions)

    // -- Incomes --
    expect(selectPlannedIncomes(state)).toHaveLength(2)
    expect(selectReceivedIncomes(state)).toHaveLength(1)
    expect(selectReceivedIncomes(state)[0]?.id).toBe("i-1")
    expect(selectPendingIncomes(state)).toHaveLength(1)
    expect(selectPendingIncomes(state)[0]?.id).toBe("i-2")
    expect(selectPlannedIncomeById("i-1")(state)?.name).toBe("Salary")
    expect(selectPlannedIncomeById("nonexistent")(state)).toBeNull()

    // -- Expenses --
    expect(selectPlannedExpenses(state)).toHaveLength(4)
    expect(selectPaidExpenses(state)).toHaveLength(2)
    expect(selectPendingExpenses(state)).toHaveLength(2)
    expect(selectMonthlyBillsExpenses(state)).toHaveLength(2)
    expect(selectCreditCardExpenses(state)).toHaveLength(1)
    expect(selectFixedCardExpenses(state)).toHaveLength(0)
    expect(selectOtherExpenses(state)).toHaveLength(1)
    expect(selectPlannedExpenseById("e-3")(state)?.name).toBe("Amazon")
    expect(selectPlannedExpenseById("nonexistent")(state)).toBeNull()

    // -- Form options --
    expect(selectPaymentMethodsOptions(state)).toHaveLength(1)
    expect(selectSubscriptionsOptions(state)).toHaveLength(1)

    // -- Summary numbers --
    expect(selectSummaryIncomeTotal(state)).toBe(6500)
    expect(selectSummaryReceivedTotal(state)).toBe(5000)
    expect(selectSummaryExpenseTotal(state)).toBe(1489.9)
    expect(selectSummaryPaidTotal(state)).toBe(1239.9)
    expect(selectSummarySubscriptionTotal(state)).toBe(500)
    expect(selectSummaryCreditCardTotal(state)).toBe(800)
    expect(selectSummaryBalance(state)).toBe(3000)
    expect(selectSummaryPendingIncomeTotal(state)).toBe(2000)
    expect(selectSummaryPendingExpenseTotal(state)).toBe(500)

    // -- Ready-state --
    expect(selectIsFinancePlanReady(state)).toBe(true)
    expect(selectIsFinanceSummaryReady(state)).toBe(true)
    expect(selectIsFinanceFormOptionsReady(state)).toBe(true)
  })
})

describe("integration: all ready-state booleans are false when data is null", () => {
  it("returns false for all ready-state selectors when data fields are null", () => {
    const state = makeRootState({
      plan: null,
      summary: null,
      formOptions: null,
    })

    expect(selectIsFinancePlanReady(state)).toBe(false)
    expect(selectIsFinanceSummaryReady(state)).toBe(false)
    expect(selectIsFinanceFormOptionsReady(state)).toBe(false)
    expect(selectPlannedIncomes(state)).toEqual([])
    expect(selectPlannedExpenses(state)).toEqual([])
    expect(selectPaymentMethodsOptions(state)).toEqual([])
    expect(selectSubscriptionsOptions(state)).toEqual([])
    expect(selectSummaryIncomeTotal(state)).toBe(0)
    expect(selectSummaryReceivedTotal(state)).toBe(0)
    expect(selectSummaryExpenseTotal(state)).toBe(0)
    expect(selectSummaryPaidTotal(state)).toBe(0)
    expect(selectSummarySubscriptionTotal(state)).toBe(0)
    expect(selectSummaryCreditCardTotal(state)).toBe(0)
    expect(selectSummaryBalance(state)).toBe(0)
    expect(selectSummaryPendingIncomeTotal(state)).toBe(0)
    expect(selectSummaryPendingExpenseTotal(state)).toBe(0)
  })
})
