import {
  Currency,
  ExpenseBucket,
  InvoiceStatus,
  PlanEntrySource,
  PrismaClient,
} from '@prisma/client'
import {
  isMonthOnOrAfter,
  monthOffset,
  monthRefFromDateString,
  planDate,
  type MonthRef,
} from './dates'
import {
  DEMO_CARDS,
  DEMO_INCOMES,
  DEMO_INSTALLMENTS,
  DEMO_INTER_TRANSACTIONS,
  DEMO_MONTHLY_BILLS,
  DEMO_NUBANK_TRANSACTIONS,
  DEMO_SUBSCRIPTIONS,
  scaleDemoAmount,
} from './demo-generic-data'

export type PaymentMethodRef = {
  id: string
  cardId: string | null
}

export type PaymentMethodMap = {
  nubank: PaymentMethodRef
  inter: PaymentMethodRef
  pix: PaymentMethodRef
}

export type SeedDemoMonthPlanParams = {
  prisma: PrismaClient
  userId: string
  monthRef: MonthRef
  monthIndex: number
  isCurrentMonth: boolean
  paymentMethods: PaymentMethodMap
  subscriptionIds: Map<string, string>
  installmentPurchaseIds: Map<string, string>
}

export type SeedDemoMonthPlanResult = {
  incomeCount: number
  billCount: number
  subscriptionExpenseCount: number
  cardTransactionCount: number
  installmentExpenseCount: number
}

function resolveInvoiceStatus(
  closingDay: number,
  planDay: number,
  isPastMonth: boolean
): InvoiceStatus {
  if (isPastMonth) return InvoiceStatus.CLOSED
  return planDay >= closingDay ? InvoiceStatus.CLOSED : InvoiceStatus.OPEN
}

function sumAmounts(items: { amount: number }[]): number {
  return items.reduce((total, item) => total + item.amount, 0)
}

function getInstallmentNumber(
  firstPurchaseDate: string,
  target: MonthRef
): number {
  const first = monthRefFromDateString(firstPurchaseDate)
  return monthOffset(first, target) + 1
}

export async function seedDemoMonthPlan(
  params: SeedDemoMonthPlanParams
): Promise<SeedDemoMonthPlanResult> {
  const {
    prisma,
    userId,
    monthRef,
    monthIndex,
    isCurrentMonth,
    paymentMethods,
    subscriptionIds,
    installmentPurchaseIds,
  } = params

  const { year, month } = monthRef
  const d = (day: number) => planDate(year, month, day)
  const isPastMonth = !isCurrentMonth
  const today = new Date().getDate()

  const plan = await prisma.monthlyPlan.create({
    data: {
      userId,
      year,
      month,
      notes: `Planejamento de ${String(month).padStart(2, '0')}/${year}`,
    },
  })

  for (const [index, income] of DEMO_INCOMES.entries()) {
    await prisma.plannedIncome.create({
      data: {
        monthlyPlanId: plan.id,
        name: income.name,
        amount: scaleDemoAmount(income.amount, monthIndex),
        currency: Currency.BRL,
        expectedDate: d(income.day),
        sortOrder: index,
        isReceived: isPastMonth,
        receivedAt: isPastMonth ? d(income.day) : undefined,
      },
    })
  }

  const scaledBills = DEMO_MONTHLY_BILLS.map((bill) => ({
    ...bill,
    amount: scaleDemoAmount(bill.amount, monthIndex),
  }))

  for (const [index, bill] of scaledBills.entries()) {
    const method = paymentMethods[bill.paymentMethodKey]
    const isCreditCardBill = bill.bucket === ExpenseBucket.CREDIT_CARD

    await prisma.plannedExpense.create({
      data: {
        monthlyPlanId: plan.id,
        name: bill.name,
        amount: bill.amount,
        currency: Currency.BRL,
        expenseBucket: bill.bucket,
        paymentMethodId: method.id,
        paymentCardId: method.cardId ?? undefined,
        dueDate: d(bill.day),
        sortOrder: index,
        isPaid: isPastMonth && !isCreditCardBill,
        paidAt: isPastMonth && !isCreditCardBill ? d(bill.day) : undefined,
      },
    })
  }

  const activeSubscriptions = DEMO_SUBSCRIPTIONS.filter((sub) => sub.active)
  let subscriptionExpenseCount = 0

  for (const [index, sub] of activeSubscriptions.entries()) {
    const hiredMonth = monthRefFromDateString(sub.hiredAt)
    if (!isMonthOnOrAfter(monthRef, hiredMonth)) continue

    const method = paymentMethods[sub.paymentMethodKey]
    const subscriptionId = subscriptionIds.get(sub.key)
    if (!subscriptionId) continue

    await prisma.plannedExpense.create({
      data: {
        monthlyPlanId: plan.id,
        name: sub.name,
        amount: scaleDemoAmount(Number(sub.price), monthIndex),
        currency: sub.currency,
        expenseBucket: ExpenseBucket.FIXED_CARD,
        paymentMethodId: method.id,
        paymentCardId: method.cardId ?? undefined,
        subscriptionId,
        source: PlanEntrySource.SUBSCRIPTION,
        isAutoGenerated: true,
        dueDate: d(sub.billingDay ?? 10),
        sortOrder: scaledBills.length + index,
        isPaid: isPastMonth,
        paidAt: isPastMonth ? d(sub.billingDay ?? 10) : undefined,
      },
    })
    subscriptionExpenseCount += 1
  }

  const nubankCard = DEMO_CARDS.find((card) => card.key === 'nubank')!
  const interCard = DEMO_CARDS.find((card) => card.key === 'inter')!

  const nubankTransactions = DEMO_NUBANK_TRANSACTIONS.map((tx, txIndex) => ({
    ...tx,
    amount: scaleDemoAmount(tx.amount, monthIndex),
    skip: monthIndex < 3 && txIndex === DEMO_NUBANK_TRANSACTIONS.length - 1,
  })).filter((tx) => !tx.skip)

  const interTransactions = DEMO_INTER_TRANSACTIONS.map((tx) => ({
    ...tx,
    amount: scaleDemoAmount(tx.amount, monthIndex),
  }))

  const activeInstallments = DEMO_INSTALLMENTS.flatMap((purchase) => {
    const installmentNumber = getInstallmentNumber(
      purchase.firstPurchaseDate,
      monthRef
    )

    if (installmentNumber < 1 || installmentNumber > purchase.installmentCount) {
      return []
    }

    return [
      {
        ...purchase,
        installmentNumber,
        monthAmount: scaleDemoAmount(purchase.monthAmount, monthIndex),
      },
    ]
  })

  const nubankInvoiceTotal =
    scaledBills.find((bill) => bill.paymentMethodKey === 'nubank')?.amount ??
    sumAmounts(nubankTransactions)

  const interInvoiceTotal =
    scaledBills.find((bill) => bill.paymentMethodKey === 'inter')?.amount ??
    sumAmounts(interTransactions) +
      sumAmounts(activeInstallments.map((item) => ({ amount: item.monthAmount })))

  const nubankInvoice = await prisma.creditCardInvoice.create({
    data: {
      userId,
      paymentCardId: paymentMethods.nubank.cardId!,
      year,
      month,
      closingDate: d(nubankCard.closingDay),
      dueDate: d(nubankCard.dueDay),
      total: nubankInvoiceTotal,
      currency: Currency.BRL,
      status: resolveInvoiceStatus(nubankCard.closingDay, today, isPastMonth),
    },
  })

  const interInvoice = await prisma.creditCardInvoice.create({
    data: {
      userId,
      paymentCardId: paymentMethods.inter.cardId!,
      year,
      month,
      closingDate: d(interCard.closingDay),
      dueDate: d(interCard.dueDay),
      total: interInvoiceTotal,
      currency: Currency.BRL,
      status: resolveInvoiceStatus(interCard.closingDay, today, isPastMonth),
    },
  })

  for (const tx of nubankTransactions) {
    await prisma.plannedExpense.create({
      data: {
        monthlyPlanId: plan.id,
        name: tx.name,
        amount: tx.amount,
        currency: Currency.BRL,
        expenseBucket: ExpenseBucket.CREDIT_CARD,
        paymentMethodId: paymentMethods.nubank.id,
        paymentCardId: paymentMethods.nubank.cardId!,
        creditCardInvoiceId: nubankInvoice.id,
        source: PlanEntrySource.CREDIT_CARD_INVOICE,
        purchaseDate: d(tx.day),
      },
    })
  }

  for (const tx of interTransactions) {
    await prisma.plannedExpense.create({
      data: {
        monthlyPlanId: plan.id,
        name: tx.name,
        amount: tx.amount,
        currency: Currency.BRL,
        expenseBucket: ExpenseBucket.CREDIT_CARD,
        paymentMethodId: paymentMethods.inter.id,
        paymentCardId: paymentMethods.inter.cardId!,
        creditCardInvoiceId: interInvoice.id,
        source: PlanEntrySource.CREDIT_CARD_INVOICE,
        purchaseDate: d(tx.day),
      },
    })
  }

  let installmentExpenseCount = 0

  for (const purchase of activeInstallments) {
    let installmentPurchaseId = installmentPurchaseIds.get(purchase.name)

    if (!installmentPurchaseId) {
      const installment = await prisma.installmentPurchase.create({
        data: {
          userId,
          paymentCardId: paymentMethods.inter.cardId!,
          name: purchase.name,
          totalAmount: purchase.totalAmount,
          currency: Currency.BRL,
          installmentCount: purchase.installmentCount,
          firstPurchaseDate: new Date(purchase.firstPurchaseDate),
        },
      })
      installmentPurchaseId = installment.id
      installmentPurchaseIds.set(purchase.name, installmentPurchaseId)
    }

    await prisma.plannedExpense.create({
      data: {
        monthlyPlanId: plan.id,
        name: purchase.name,
        amount: purchase.monthAmount,
        currency: Currency.BRL,
        expenseBucket: ExpenseBucket.CREDIT_CARD,
        paymentMethodId: paymentMethods.inter.id,
        paymentCardId: paymentMethods.inter.cardId!,
        creditCardInvoiceId: interInvoice.id,
        installmentPurchaseId,
        installmentNumber: purchase.installmentNumber,
        installmentTotal: purchase.installmentCount,
        source: PlanEntrySource.INSTALLMENT,
        purchaseDate: d(purchase.purchaseDay),
      },
    })
    installmentExpenseCount += 1
  }

  return {
    incomeCount: DEMO_INCOMES.length,
    billCount: scaledBills.length,
    subscriptionExpenseCount,
    cardTransactionCount: nubankTransactions.length + interTransactions.length,
    installmentExpenseCount,
  }
}
